const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];let client;let currentProfile;let allUsers=[];
const initials=value=>String(value||'P').split(/\s|@/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const date=value=>value?new Date(value).toLocaleDateString():'—';
function status(message,type=''){const e=$('#admin-status');e.textContent=message;e.className=type?`status-${type}`:''}
async function loadLibrary(){if(window.supabase?.createClient)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function render(filter=''){const term=filter.toLowerCase().trim();const users=allUsers.filter(u=>!term||String(u.display_name||'').toLowerCase().includes(term)||String(u.email||'').toLowerCase().includes(term));$('#user-rows').innerHTML=users.map(user=>{const self=user.id===currentProfile.id;return `<tr><td><div class="user-cell"><span class="user-avatar">${initials(user.display_name||user.email)}</span><span class="user-name"><b>${user.display_name||'Unnamed Player'}</b>${self?'<small>CURRENT ACCOUNT</small>':''}</span></div></td><td>${user.email||'—'}</td><td><select class="role-select" data-role-user="${user.id}"><option value="user" ${user.role==='user'?'selected':''}>User</option><option value="admin" ${user.role==='admin'?'selected':''}>Admin</option></select></td><td>${date(user.created_at)}</td><td><button class="save-role" data-save-user="${user.id}">Update Role</button></td></tr>`}).join('');$$('[data-save-user]').forEach(b=>b.addEventListener('click',()=>saveRole(b.dataset.saveUser)))}
async function loadUsers(){status('Loading users...');const {data,error}=await client.schema('pedro').from('profiles').select('id,email,display_name,role,created_at,updated_at').order('created_at',{ascending:true});if(error)return status(error.message,'error');allUsers=data||[];$('#total-users').textContent=allUsers.length;$('#total-admins').textContent=allUsers.filter(u=>u.role==='admin').length;$('#total-standard').textContent=allUsers.filter(u=>u.role!=='admin').length;render($('#user-search').value);status(`${allUsers.length} account${allUsers.length===1?'':'s'} loaded.`)}
async function saveRole(id){const button=$(`[data-save-user="${id}"]`);const select=$(`[data-role-user="${id}"]`);button.disabled=true;button.textContent='Saving...';const {error}=await client.schema('pedro').rpc('set_user_role',{target_user_id:id,new_role:select.value});button.disabled=false;button.textContent='Update Role';if(error)return status(error.message,'error');status('Role updated.','success');await loadUsers()}
async function init(){try{await loadLibrary();client=window.pedroSupabase||window.supabase.createClient(PEDRO_CONFIG.supabaseUrl,PEDRO_CONFIG.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data:{session}}=await client.auth.getSession();if(!session)return;const {data:profile,error}=await client.schema('pedro').from('profiles').select('id,email,display_name,role').eq('id',session.user.id).single();if(error||profile?.role!=='admin'){$('#access-message h1').textContent='Administrator Access Required';$('#access-message p').textContent='This account does not have permission to view User Management.';return}currentProfile=profile;$('#admin-name').textContent=profile.display_name||profile.email;$('#admin-email').textContent=profile.email||session.user.email;$('#admin-avatar').textContent=initials(profile.display_name||profile.email);$('#access-message').hidden=true;$('#admin-app').hidden=false;await loadUsers()}catch(error){$('#access-message h1').textContent='Administration Error';$('#access-message p').textContent=error.message}}
$('#refresh-users').addEventListener('click',loadUsers);$('#user-search').addEventListener('input',e=>render(e.target.value));init();
