const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const config=window.PEDRO_CONFIG||{};let sb=null;let visibility="private",rule="follow";
const demoTables=[{name:"Bayou Table 1",host:"PoppaT",rule:"Follow Suit",score:52,players:"3 / 4"},{name:"Cajun Crew",host:"Lafitte",rule:"Cut-Throat",score:104,players:"2 / 4"},{name:"Golden Meadow",host:"TroutMan",rule:"Follow Suit",score:52,players:"4 / 4"},{name:"Thibodaux Kings",host:"RedFish",rule:"Cut-Throat",score:52,players:"1 / 4"}];
const titles={lobby:"Game Lobby",create:"Create Table",join:"Join Table",tournaments:"Tournaments",profile:"Profile"};
function toast(m){const e=$("#toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function setStatus(m,t="info"){const e=$("#auth-status");e.textContent=m;e.style.color=t==="error"?"#ff827a":t==="success"?"#76d99a":"#d8b45b"}
function friendly(e){const m=String(e?.message||"Something went wrong.");if(/invalid login credentials/i.test(m))return"Incorrect email address or password.";if(/email not confirmed/i.test(m))return"Confirm the account from the email sent by Pedro, then sign in.";return m}
async function client(){if(sb)return sb;if(!window.supabase?.createClient){await new Promise((ok,no)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";s.onload=ok;s.onerror=no;document.head.appendChild(s)})}sb=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sb}
function showView(id){$$('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function showScreen(name){$$('.screen').forEach(s=>s.classList.remove('active'));$('#screen-'+name).classList.add('active');$$('.nav-button[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));$('#page-title').textContent=titles[name]||'Pedro Online'}
function enterLobby(email="Pedro Player"){showView('#app-view');showScreen('lobby');const label=email.split('@')[0]||'Pedro Player';$('#user-name').textContent=label;$('#profile-email').textContent=email;const i=label.slice(0,2).toUpperCase();$('#user-initials').textContent=i;$('#profile-initials').textContent=i;renderTables()}
function renderTables(){const body=$('#table-rows');body.innerHTML=demoTables.map((t,i)=>`<div class="table-row"><div><b>${t.name}</b><small>${t.players==='4 / 4'?'Spectators allowed':'Seat available'}</small></div><span>${t.host}</span><span><i class="rule-pill">${t.rule}</i></span><span>${t.score}</span><span>${t.players}</span><button class="${t.players==='4 / 4'?'secondary':'join-button'}" data-join-index="${i}">${t.players==='4 / 4'?'WATCH':'JOIN'}</button></div>`).join('');$('#empty-tables').hidden=demoTables.length>0;$$('[data-join-index]').forEach(b=>b.addEventListener('click',()=>openGame(demoTables[Number(b.dataset.joinIndex)])))}
function code(){return ['BAYOU','PEDRO','CAJUN','DELTA'][Math.floor(Math.random()*4)]+Math.floor(10+Math.random()*90)}
function openGame(t){$('#game-table-name').textContent=t.name;$('#game-room-label').textContent=t.room?`Private Room · ${t.room}`:'Public Table';$('#game-rule').textContent=t.rule;$('#game-winning-score').textContent=t.score;showView('#game-view')}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;if(!email||!password)return setStatus('Enter both email and password.','error');setStatus('Signing in...');try{const c=await client();const{error}=await c.auth.signInWithPassword({email,password});if(error)throw error;setStatus('Sign-in successful.','success');enterLobby(email)}catch(x){setStatus(friendly(x),'error')}});
$('#create-account').addEventListener('click',async()=>{const email=$('#login-email').value.trim(),password=$('#login-password').value;if(!email||!password)return setStatus('Enter an email and password first.','error');try{const c=await client();const{data,error}=await c.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session)enterLobby(email);else setStatus('Account created. Check email to confirm it, then sign in.','success')}catch(x){setStatus(friendly(x),'error')}});
$('#forgot-password').addEventListener('click',async()=>{const email=$('#login-email').value.trim();if(!email)return setStatus('Enter the account email first.','error');try{const c=await client();const{error}=await c.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(error)throw error;setStatus('Password-reset email sent.','success')}catch(x){setStatus(friendly(x),'error')}});
$('#sign-out').addEventListener('click',async()=>{try{(await client()).auth.signOut()}finally{showView('#login-view')}});
$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.screen)));
$$('[data-visibility]').forEach(b=>b.addEventListener('click',()=>{visibility=b.dataset.visibility;$$('[data-visibility]').forEach(x=>x.classList.toggle('selected',x===b));$('#room-code-field').hidden=visibility==='public'}));
$$('[data-rule]').forEach(b=>b.addEventListener('click',()=>{rule=b.dataset.rule;$$('[data-rule]').forEach(x=>x.classList.toggle('selected',x===b))}));
$('#winning-score').addEventListener('change',e=>$('#custom-score-field').hidden=e.target.value!=='custom');
$('#new-room-code').addEventListener('click',()=>$('#room-code').value=code());
$('#create-table-form').addEventListener('submit',e=>{e.preventDefault();const score=$('#winning-score').value==='custom'?Number($('#custom-score').value):Number($('#winning-score').value);if(!score||score<1)return toast('Enter a valid winning score');const t={name:$('#table-name').value.trim()||'Pedro Table',host:$('#user-name').textContent,rule:rule==='follow'?'Follow Suit':'Cut-Throat',score,players:'1 / 4',room:visibility==='private'?$('#room-code').value:''};if(visibility==='public')demoTables.unshift(t);openGame(t)});
$('#join-table-form').addEventListener('submit',e=>{e.preventDefault();const room=$('#join-room-code').value.trim().toUpperCase();if(!room)return toast('Enter a room code');openGame({name:'Private Pedro Table',rule:'Follow Suit',score:52,room})});
$('#refresh-tables').addEventListener('click',()=>{renderTables();toast('Tables refreshed')});$('#leave-table').addEventListener('click',()=>{showView('#app-view');showScreen('lobby')});$('#game-home').addEventListener('click',()=>{showView('#app-view');showScreen('lobby')});
(async()=>{$('#room-code').value=code();renderTables();try{const c=await client();const{data}=await c.auth.getSession();if(data.session)enterLobby(data.session.user.email);c.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session)enterLobby(session.user.email);if(event==='SIGNED_OUT')showView('#login-view')})}catch(e){setStatus(friendly(e),'error')}})();
