(() => {
  if (window.__pedroSeatHandFixV6) return;
  window.__pedroSeatHandFixV6 = true;
  const Game=window.PedroGameState;if(!Game)return;
  const seatLabels={south:'South',west:'West',north:'North',east:'East'}, suitNames={'♥':'Hearts','♦':'Diamonds','♣':'Clubs','♠':'Spades'};
  const currentName=()=>document.querySelector('#user-name')?.textContent.trim()||'Pedro Player';
  const playerSeat=state=>Object.keys(state.seats||{}).find(seat=>state.seats[seat]===currentName())||null;
  const active=()=>document.querySelector('#game-view')?.classList.contains('active');
  const red=suit=>suit==='♥'||suit==='♦';
  let dragId=null;

  function styles(){if(document.querySelector('#seat-hand-fix-v6'))return;const style=document.createElement('style');style.id='seat-hand-fix-v6';style.textContent=`
    .your-hand-wrap{position:absolute;z-index:32;left:50%;bottom:3px;transform:translateX(-50%);width:min(84%,980px);text-align:center}.your-hand-label{display:inline-flex;margin-bottom:5px;padding:4px 9px;border:1px solid #d9ad4c;border-radius:13px;background:#171108;color:#f5d36f;font-size:9px;font-weight:900;letter-spacing:.1em}.your-hand{display:flex;justify-content:center;align-items:flex-end}.your-card{position:relative;width:72px;height:104px;margin-left:-17px;border:1px solid #d0d0d0;border-radius:8px;background:linear-gradient(#fff,#eee9df);color:#111;box-shadow:0 8px 18px #0008;transform:rotate(var(--rot));transform-origin:bottom center;cursor:grab}.your-card:first-child{margin-left:0}.your-card.red{color:#c62d34}.your-card b{position:absolute;left:7px;top:5px;font-size:17px}.your-card i{position:absolute;inset:0;display:grid;place-items:center;font-size:33px;font-style:normal}.your-card.dragging{opacity:.45}.your-card.drop-target{outline:3px solid #eeb84b;transform:translateY(-8px) rotate(var(--rot))}.seat-hand-note{display:block;margin-top:4px;color:#d3dcdd;font-size:9px}.dealer-marker-v6{position:absolute;z-index:40;padding:4px 8px;border:1px solid #d5aa49;border-radius:14px;background:#251b08;color:#f4d06b;font-size:9px;font-weight:900}.dealer-marker-v6{right:-66px;top:3px}.east-seat .dealer-marker-v6{left:-66px;right:auto}.bidding-v6{margin:0 0 10px;padding:11px;border:1px solid #40565e;border-radius:9px;background:#091519}.bidding-v6-title{display:flex;justify-content:space-between;color:#9fd9ef;font-size:10px;font-weight:900}.bidding-v6-list{display:grid;gap:5px;margin-top:8px}.bidding-v6-row{display:flex;justify-content:space-between;padding:7px;border:1px solid #304249;border-radius:6px;color:#e7eeec;font-size:11px}.bidding-v6-actions{display:grid;grid-template-columns:repeat(4,minmax(42px,1fr));gap:6px;margin-top:9px}.bidding-v6-actions button{min-height:39px;border:1px solid #4d6670;border-radius:7px;background:#142a32;color:#fff;font-size:11px;font-weight:900}.bidding-v6-actions .special{grid-column:span 2;border-color:#8c7134;background:#33280f;color:#f5d77e}.trump-v6{grid-template-columns:1fr 1fr}.trump-v6 button{min-height:46px;background:#f1f4f4;color:#111}.trump-v6 .red{color:#c62c34}#stable-hand,#v4-visible-hand,#v3-visible-hand{display:none!important}
  `;document.head.appendChild(style)}

  function status(state){const dealer=state.seats?.[state.dealer]||seatLabels[state.dealer],waiting=state.phase==='bidding'?(state.seats?.[state.currentBidder]||seatLabels[state.currentBidder]):state.phase==='trump'?(state.seats?.[state.winner]||seatLabels[state.winner]):state.phase==='dealer-discard'?dealer:'Waiting for players',high=state.highBid?`${state.highBid.amount} by ${state.seats?.[state.highBid.seat]||seatLabels[state.highBid.seat]}`:'No bid',trump=state.trump?suitNames[state.trump]:'Not selected';const phase=String(state.phase||'waiting').replace('-',' ').toUpperCase();const center=document.querySelector('#center-phase');if(center)center.textContent=`${phase} · Waiting on ${waiting}`;const details=document.querySelector('.center-status small');if(details)details.innerHTML=`<b>Dealer: ${dealer}</b><b>Waiting: ${waiting}</b><b>High bid: ${high}</b><b>Trump: ${trump}</b>`;const badge=document.querySelector('#phase-badge');if(badge)badge.textContent=`${phase} · ${waiting}`}
  function dealer(state){document.querySelectorAll('.dealer-marker-v6').forEach(e=>e.remove());const seat=document.querySelector(`[data-table-seat="${state.dealer}"]`);if(!seat)return;const badge=document.createElement('span');badge.className='dealer-marker-v6';badge.textContent='DEALER';seat.appendChild(badge)}
  function hand(state){let wrap=document.querySelector('#your-hand-wrap');if(!wrap){wrap=document.createElement('section');wrap.id='your-hand-wrap';wrap.className='your-hand-wrap';wrap.innerHTML='<span class="your-hand-label">YOUR HAND</span><div id="your-hand" class="your-hand"></div><small id="your-hand-note" class="seat-hand-note"></small>';document.querySelector('.professional-table')?.appendChild(wrap)}const seat=playerSeat(state),cards=seat?(state.hands?.[seat]||[]):[];document.querySelector('#your-hand-note').textContent=seat?`You are seated East/West/North/South as ${seatLabels[seat]}. Your cards stay at the bottom for easier play.`:'Choose a seat to receive a hand.';const target=document.querySelector('#your-hand');target.innerHTML=cards.map((card,index)=>`<button draggable="true" class="your-card ${red(card.suit)?'red':''}" data-card-id="${card.id}" style="--rot:${(index-(cards.length-1)/2)*2}deg"><b>${card.rank}<br>${card.suit}</b><i>${card.suit}</i></button>`).join('');wrap.hidden=!cards.length;target.querySelectorAll('.your-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragId=card.dataset.cardId;card.classList.add('dragging')});card.addEventListener('dragend',()=>{dragId=null;target.querySelectorAll('.your-card').forEach(item=>item.classList.remove('dragging','drop-target'))});card.addEventListener('dragover',event=>{event.preventDefault();card.classList.add('drop-target')});card.addEventListener('dragleave',()=>card.classList.remove('drop-target'));card.addEventListener('drop',event=>{event.preventDefault();const to=card.dataset.cardId;if(!dragId||dragId===to)return;const ids=cards.map(item=>item.id),fromIndex=ids.indexOf(dragId),toIndex=ids.indexOf(to);const[moved]=ids.splice(fromIndex,1);ids.splice(toIndex,0,moved);Game.reorderHand(seat,ids)})})}
  function bidding(state){let panel=document.querySelector('#bidding-v6');if(!panel){panel=document.createElement('section');panel.id='bidding-v6';panel.className='bidding-v6';document.querySelector('#table-control-frame')?.prepend(panel)}const seat=playerSeat(state);let actions='';if(state.phase==='bidding'){actions=`<div class="bidding-v6-actions"><button data-v6bid="pass" ${seat!==state.currentBidder?'disabled':''}>PASS</button>${Game.allowed(seat).map(value=>`<button class="${value==='14/28'?'special':''}" data-v6bid="${value}">${value}</button>`).join('')}</div>`}else if(state.phase==='trump'&&seat===state.winner){actions=`<div class="bidding-v6-actions trump-v6">${['♥','♠','♦','♣'].map(suit=>`<button class="${red(suit)?'red':''}" data-v6trump="${suit}">${suit} ${suitNames[suit]}</button>`).join('')}</div>`}panel.innerHTML=`<div class="bidding-v6-title"><span>BIDDING HISTORY</span><b>${state.bids?.length||0}</b></div><div class="bidding-v6-list">${state.bids?.length?state.bids.map(item=>`<div class="bidding-v6-row"><span>${item.player||state.seats?.[item.seat]||'Player'}</span><b>${item.amount}</b></div>`).join(''):'<div class="bidding-v6-row"><span>No bids yet</span><b>—</b></div>'}</div>${actions}`}
  function render(){if(!active())return;const state=Game.snap();status(state);dealer(state);hand(state);bidding(state)}
  document.addEventListener('click',event=>{const bid=event.target.closest('[data-v6bid]');if(bid){const state=Game.snap(),value=bid.dataset.v6bid;const result=Game.bid(playerSeat(state),value==='pass'?'pass':value);if(!result.ok)alert(result.message);render()}const trump=event.target.closest('[data-v6trump]');if(trump){Game.trump(trump.dataset.v6trump);render()}},true);window.addEventListener('pedro:state',render);window.addEventListener('focus',()=>setTimeout(render,50));styles();setTimeout(render,100)})();
