(() => {
  if (window.__pedroRejoinLobbyV2) return;
  window.__pedroRejoinLobbyV2 = true;
  let rows=[];
  const normalize=row=>({id:row.id,name:row.table_name||'Pedro Table',host:row.host_display_name||row.host_email||'Pedro Player',rule:row.play_style==='cut'?'Cut-Throat':'Follow Suit',score:Number(row.winning_score||52),players:`${Number(row.player_count||1)} / 4`,room:row.room_code||''});
  function render(){const body=document.querySelector('#table-rows');if(!body)return;const tables=rows.map(normalize);body.innerHTML=tables.map((table,index)=>{const active=window.PedroGameState?.snap()?.tableId===table.id;return`<div class="table-row"><div><b>${table.name}</b><small>${active?'Game in progress · Rejoin available':'Seat available'}</small></div><span>${table.host}</span><span><i class="rule-pill">${table.rule}</i></span><span>${table.score}</span><span>${table.players}</span><button class="join-button" data-rejoin-table="${index}">${active?'REJOIN':'JOIN'}</button></div>`}).join('');body.querySelectorAll('[data-rejoin-table]').forEach(button=>button.onclick=()=>{const table=tables[Number(button.dataset.rejoinTable)];PedroGameState.setTable(table);sessionStorage.setItem('pedro.active.view.v1',JSON.stringify({view:'game',title:table.name,room:table.room?'Private Room':'Public Table'}));window.pedroGame?.open(table,'join');setTimeout(()=>window.dispatchEvent(new CustomEvent('pedro:state',{detail:PedroGameState.snap()})),80)})}
  async function load(){try{const client=await PedroCore.getClient();const{data,error}=await client.schema('pedro').from('public_tables').select('*').eq('visibility','public').in('status',['open','playing']).order('created_at',{ascending:false});if(error)throw error;rows=data||[];render()}catch(error){console.error('Public table load failed:',error)}}
  document.querySelector('#refresh-tables')?.addEventListener('click',event=>{event.stopImmediatePropagation();load()},true);document.addEventListener('click',event=>{if(event.target.closest('[data-screen="lobby"],#leave-table,#game-home'))setTimeout(load,80)},true);load();
})();
