(() => {
  if (window.__pedroLobbyLoaded) return;
  window.__pedroLobbyLoaded = true;
  let rows = [];
  function normalize(row){return{id:row.id,name:row.table_name||'Pedro Table',host:row.host_display_name||row.host_email||'Pedro Player',rule:row.play_style==='cut'?'Cut-Throat':'Follow Suit',score:Number(row.winning_score||52),players:`${Number(row.player_count||1)} / 4`,room:row.room_code||''}}
  function render(){const body=document.querySelector('#table-rows');if(!body)return;const tables=rows.map(normalize);body.innerHTML=tables.map((t,i)=>`<div class="table-row"><div><b>${t.name}</b><small>Seat available</small></div><span>${t.host}</span><span><i class="rule-pill">${t.rule}</i></span><span>${t.score}</span><span>${t.players}</span><button class="join-button" data-mod-live-table="${i}">JOIN</button></div>`).join('');document.querySelectorAll('[data-mod-live-table]').forEach(button=>button.onclick=()=>{const table=tables[Number(button.dataset.modLiveTable)];window.pedroGame?.open(table,'join')})}
  async function load(){try{const client=await PedroCore.getClient();const {data,error}=await client.schema('pedro').from('public_tables').select('*').eq('visibility','public').eq('status','open').order('created_at',{ascending:false});if(error)throw error;rows=data||[];render()}catch(error){console.error('Public table load failed:',error)}}
  async function save(){const publicSelected=document.querySelector('[data-visibility="public"]')?.classList.contains('selected');if(!publicSelected)return;const client=await PedroCore.getClient();const {data:auth}=await client.auth.getSession();const user=auth.session?.user;if(!user)return;const score=document.querySelector('#winning-score');const payload={table_name:document.querySelector('#table-name')?.value.trim()||'Pedro Table',host_id:user.id,host_email:user.email,host_display_name:document.querySelector('#user-name')?.textContent.trim()||user.email.split('@')[0],visibility:'public',play_style:document.querySelector('[data-rule].selected')?.dataset.rule||'follow',winning_score:score?.value==='custom'?Number(document.querySelector('#custom-score')?.value||52):Number(score?.value||52),lead_trump:Boolean(document.querySelector('#lead-trump')?.checked),player_count:1,status:'open',updated_at:new Date().toISOString()};const {data,error}=await client.schema('pedro').from('public_tables').insert(payload).select().single();if(error)return console.error('Public table save failed:',error);rows=[data,...rows];}
  document.querySelector('#create-table-form')?.addEventListener('submit',()=>setTimeout(save,0),true);
  document.querySelector('#refresh-tables')?.addEventListener('click',event=>{event.stopImmediatePropagation();load()},true);
  document.addEventListener('click',event=>{if(event.target.closest('[data-screen="lobby"],#leave-table,#game-home'))setTimeout(load,80)},true);
  load();
})();
